server:
  port: 9443
  ssl:
      key-store: file:///<<full path to spring-rest-demo.jks>>
      key-store-password: notprod
      key-password: notprod

logging:
  file: logs/spring-rest-demo.log
  level:
    root: INFO
    org.springframework.security: DEBUG